// <auto-generated />
using System;
using Aquaculture.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aquaculture.Infrastructure.Migrations
{
    [DbContext(typeof(AquacultureDbContext))]
    [Migration("20230401140516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aquaculture.Domain.FishTankAggregate.FishTank", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WaterMeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FishTanks", (string)null);
                });

            modelBuilder.Entity("Aquaculture.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Aquaculture.Domain.WaterMeasurementAggreate.WaterMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FishTankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WaterMeasurements", (string)null);
                });

            modelBuilder.Entity("Aquaculture.Domain.WaterMeasurementAggreate.WaterMeasurement", b =>
                {
                    b.OwnsOne("Aquaculture.Domain.WaterMeasurementAggreate.ValueObjects.WaterParams", "WaterParams", b1 =>
                        {
                            b1.Property<Guid>("WaterMeasurementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("Acidity")
                                .HasColumnType("real");

                            b1.Property<float>("Alkalinity")
                                .HasColumnType("real");

                            b1.Property<float>("Ammonia")
                                .HasColumnType("real");

                            b1.Property<float>("CarbonDioxide")
                                .HasColumnType("real");

                            b1.Property<float>("DissolvedOxygen")
                                .HasColumnType("real");

                            b1.Property<float>("Temperature")
                                .HasColumnType("real");

                            b1.HasKey("WaterMeasurementId");

                            b1.ToTable("WaterMeasurements");

                            b1.WithOwner()
                                .HasForeignKey("WaterMeasurementId");
                        });

                    b.Navigation("WaterParams")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
