@host=https://localhost:7029

GET {{host}}/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhN2MwMjg0ZS1jMGFmLTQ5ZDgtYmE1Yi0xMTkyNDBjNzhhYTIiLCJuYW1lIjoiQW5kcmV5IFZvbHluaW4iLCJqdGkiOiIxMmEzODE5Mi01NjZmLTQyZDgtODcwYS02NmE5MGUyNTJjZGYiLCJleHAiOjE2NzU3ODIyNzEsImlzcyI6IkFxdWFjdWx0dXJlIiwiYXVkIjoiQXF1YWN1bHR1cmUifQ.azAlRx3OLsUIGKnqJvR86EfM2Hv4eKFX8UzCH5Sazu0