version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
  web:
    stdin_open: true
    volumes:
      - './aquaculture.web:/app'
      - /app/node_modules
    ports:
      - "5001:3000"
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"