version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}aquacultureapi
    build:
      context: .
      dockerfile: Aquaculture.Api\Dockerfile
  web:
    image: web
    build:
      context: .\aquaculture.web
      dockerfile: Dockerfile
  proxy:
    image: nginx:mainline